### ISSUE TITLE
New file added does not trigger reload

### ISSUE THREAD

**Issue by Alex-Intection** [txchen/light-server#28]
Hello.
First of all, you have an awesome package... the best and most useful live reload package + server.
But unfortunately there is a small inconvenience. 
If someone adds a file that is matched by the glob package and your server is already running, the reload is not triggered. Is this by intention?

Thank you very much.

**Comment by txchen** [comment]
@Alex-Intection First of all, thanks for the kind words!

I think you are right, this should be a bug. Let me try to figure out how to fix it. Thanks for the issue!

**Comment by lwchkg** [comment]
How about using https://github.com/paulmillr/chokidar instead of the fs.watch?

**Comment by Alex-Intection** [comment]
https://github.com/shama/gaze has less dependencies... if this is an issue.

**Comment by txchen** [comment]
gaze looks promising, I will try to use it to replace my own dead simple watcher.

**Comment by txchen** [comment]
Implemented in 2.4.0

**Comment by richardgazdik** [comment]
Same thing happens when you create a new folder and add a new file to it. 
Eg. I have the following watchexp: `src/**/*.scss # npm run styles:dev # reloadcss` and when I create a new folder inside `src/components/` and add new file there `src/components/buttons/buttons.scss` the bounded command is not triggered.
