### ISSUE TITLE
Triggers reload for HTML but does not reflect change

### ISSUE THREAD

**Issue by MelodicCrypter** [txchen/light-server#50]
Actually, everything is working perfectly, and it also triggers reload whenever I hit save, but the changes I made inside HTML does not reflect in the browser. By the way, I'm using google's Workbox for PWA features.

**Comment by txchen** [comment]
@MelodicCrypter mind sharing an example to repro this?

**Comment by MelodicCrypter** [comment]
@txchen thanks for response. Here's my final repo [EWWB](https://github.com/MelodicCrypter/Express-Workbox-Webpack-Babel-Scaffold) which also serves as reprod for this issue, cause I have no other option but push it and use LS as my final tool (for static reload). **Light-Server** is awesome by the way! I used Browser-Refresh and Browser-Sync, but I find Light-Server to be fast and easy to use.

Just clone the repo then follow the **Usage** area.

**Comment by txchen** [comment]
@MelodicCrypter I took a look at your repo, and I can repro your issue.
However I think the root cause is in the service worker cache, the livereload.js lightserver injected works as expected. When you hit the save the first time, it reloads but the cache is still the old version, after this request, it will load the new version, but not updating the page. Then you save again, it shows the cache again, but this time the cache was updated in previous refresh.

https://gist.github.com/Rich-Harris/fd6c3c73e6e707e312d7c5d7d0f3b2f9 mentioned a workaround, by enable the `update on refresh` in dev tools, but it will make the refresh slower.
